version: '3.7'

services:
  web:
    image: web
    build:
      target: production
      context: .
    env_file:
      - .env.prod
    ports:
      - 8000:80
    command: /opt/app/start-server.sh
    networks:
      api:
    depends_on:
      - db
  db:
    image: postgres:12.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery_db
    volumes: 
      - pgdata:/var/lib/postgresql/pgdata
    networks:
      api:
volumes:
  pgdata:
networks:
  api: