name: CI CD pipeline

on:
  push:
    branches:
      - '**'

jobs:        
  # Run lints and tests
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v2.0.3

      - name: Build testing environment
        run: docker-compose -f docker-compose.test.yml build
        
      - name: Run PEP8 lint and tests
        run: docker-compose -f docker-compose.test.yml run sut
  deploy:
    runs-on: ubuntu-latest
    needs: lint-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: ${{ secrets.HEROKU_USER }}
          api_key: ${{ secrets.HEROKU_AUTH_TOKEN }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: ''
